config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  resources :photos, only: [:create]
  resources :plays, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :content

  def self.get_photos_collection
    Photo.all.order("RANDOM()").limit(10).collect(&:content)
  end
end

app/models/play.rb
class Play < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    params[:photo][:content].each do |image|
      Photo.create(content: image)
    end

    redirect_to root_path, notice: "Photos uploaded."
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def index
    @plays = Play.all
    @image_collection = Photo.get_photos_collection.collect{|pic| url_for(pic) }.to_json 
  end

  def create
    Play.create(
      number: params[:number],
      image_url: params[:image_url]
    )
    render plain: "Data captured.."
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @photo = Photo.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
  %nav.navbar.navbar-dark.bg-inverse
    %ul.nav.navbar-nav.clearfix
      %li.nav-item
        %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
          \ &#9776;
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to "Rails bootstrap", root_path, class: 'navbar-brand'
      %ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Wish Pond Assignment'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Wish Pond Assignment'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/plays/index.html.erb
<script>
  var image_collection = <%= @image_collection.html_safe%>
</script>
<h1 id="coundown-timer"></h1>

<img src="" id="image_section" style="width:100px;height: 100px;"/>

<br/>
<br/>
<br/>

<button onClick="captureData()" class="btn btn-primary"> Play </button>
<br/>
<br/>

<table class="table" id="plays-listing">
  <thead>
    <tr>
      <td>Timer value</td>
      <td>Image</td>
    </tr>
  </thead>
  <tbody>
    <% @plays.each do |play|%>
      <tr>
        <td><%= play.number%></td>
        <td><img src="<%= play.image_url%>" style="width: 200px;height: 200px;" /></td>
      </tr>
    <%end%>  
  </tbody>
</table>

app/views/visitors/index.html.erb
<div class="row d-flex justify-content-end">
  <%= link_to "Play", plays_path%>
</div>
<h3>Welcome</h3>
<%= form_for @photo do |f| %>
  <p>
    <%= f.label "Add some file"%><br/>
    <%= f.file_field :content, multiple: true %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>